AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0533f2ba8a1995cf9
      InstanceType: t2.micro
      KeyName: Deniz-clarusway-key
      SecurityGroups:
        - cfn-demo-sg
      Tags:
        - Key: Name 
          Value: Deniz-First-Cloudformation-Stack-Instance  